### ISSUE TITLE
Input via mic or line in through AudioSystem?

### ISSUE THREAD

**Issue by anton-johansson** [sheinbergon/jna-aac-encoder#11]
Is the input format that you get when reading input from the mic or line-in supported? I'd test myself, but I haven't gotten around to upgrade to Java 10, and this library seems to be built with Java 10 as the target. :)

What I want to do is basically read input audio and push it directly to an output stream over HTTP, but I need to convert it to a better format, such as AAC.

**Comment by sheinbergon** [comment]
Well, no real issue in here. Closing.
