### ISSUE TITLE
Support JDK1.8

### ISSUE THREAD

**Issue by HaoHaoDaYouXi** [sheinbergon/jna-aac-encoder#22]
Hopes to support JDK1.8. Currently, the mainstream version is still 1.8. Thank you very much

**Comment by sheinbergon** [comment]
Hello @HaoHaoDaYouXi and thank you for the interest in this project. 

Could you share what's preventing you from upgrading to 11 LTS?
 
Given that 17 is the most recent LTS version, aligning my codebase to a 2014 JVM version is something I'd rather avoid though workarounds might exist...

**Comment by HaoHaoDaYouXi** [comment]
I hope to upgrade, but if it is an old project, it cannot be integrated into development, and if it is upgraded, the possible problems will not be evaluated

**Comment by sheinbergon** [comment]
@HaoHaoDaYouXi I will see what I can do. Will the company you work for be willing to sponsor this development effort?

**Comment by HaoHaoDaYouXi** [comment]
I'm sorry to disappoint you. I should not sponsor this matter. I'm sorry to bother you.

**Comment by sheinbergon** [comment]
@HaoHaoDaYouXi Ok. I will keep you posted as to weather or not this is resolveable or not

**Comment by HaoHaoDaYouXi** [comment]
Okay, thank you very much

**Comment by sheinbergon** [comment]
@HaoHaoDaYouXi ok, I will create a release artifact that matches Jdk 1.8. Change set was not that big.
Note that I do not obligate to remain in JDK 8, which is no 8 years old, and it is likely that future version will upgrade to JDK 11 back. You will always have stable JDK 8 artifacts supporting FDK-AAC 0.1.6, though.

I will create a release soon

**Comment by HaoHaoDaYouXi** [comment]
Thank you very much

**Comment by sheinbergon** [comment]
Fixed in #23, matching 0.1.9 artifact should be available from maven central. Please let me know if it's working ok you
